# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-22 21:32
from __future__ import unicode_literals

import array_field_select.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('types', array_field_select.fields.ArrayField(base_field=models.IntegerField(blank=True, choices=[(0, 'Full Time'), (1, 'Part Time'), (2, 'Contract'), (3, 'Permanent'), (4, 'Temporary')], null=True), blank=True, default=[], null=True, size=None)),
                ('experience_from', models.IntegerField(blank=True, default=None, null=True)),
                ('experience_to', models.IntegerField(blank=True, default=None, null=True)),
                ('salary_from', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=11, null=True)),
                ('salary_to', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=11, null=True)),
                ('descr', models.TextField(blank=True, null=True)),
                ('source', models.TextField(blank=True, null=True)),
                ('source_hash', models.CharField(blank=True, default=None, max_length=255, null=True, unique=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='users.Company')),
                ('industry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='common.Industry')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='common.Location')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='common.Role')),
            ],
            options={
                'ordering': ('-modified', 'name'),
            },
        ),
    ]
