# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-16 07:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('job_profiles', '0002_auto_20180129_1733'),
        ('vacancies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True)),
                ('status', models.IntegerField(choices=[(0, 'New'), (1, 'Sent'), (2, 'Sent with error')], default=0)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('job_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_profile', to='job_profiles.JobProfile')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_from', to='vacancies.Vacancy')),
            ],
        ),
    ]
