# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-16 06:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='status',
            field=models.IntegerField(choices=[(0, 'New'), (1, 'Sent'), (2, 'Sent with error')], default=0),
        ),
    ]
