# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-16 07:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_message_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='user',
        ),
        migrations.RemoveField(
            model_name='message',
            name='user_to',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
