export const AUTH_LOGIN_USER_REQUEST = 'AUTH_LOGIN_USER_REQUEST';
export const AUTH_LOGIN_USER_FAILURE = 'AUTH_LOGIN_USER_FAILURE';
export const AUTH_LOGIN_USER_SUCCESS = 'AUTH_LOGIN_USER_SUCCESS';
export const AUTH_LOGOUT_USER = 'AUTH_LOGOUT_USER';

export const JOB_PROFILE_LIST = 'JOB_PROFILE_LIST';
export const JOB_PROFILE_CREATE = 'JOB_PROFILE_CREATE';
export const JOB_PROFILE_UPDATE = 'JOB_PROFILE_UPDATE';
export const JOB_PROFILE_MARK_DEFAULT = 'JOB_PROFILE_MARK_DEFAULT';
export const JOB_PROFILE_DELETE = 'JOB_PROFILE_DELETE';
export const JOB_PROFILE_SHOW_EDIT_MODAL = 'JOB_PROFILE_SHOW_EDIT_MODAL';
export const JOB_PROFILE_HIDE_EDIT_MODAL = 'JOB_PROFILE_HIDE_EDIT_MODAL';
export const JOB_PROFILE_SELECT = 'JOB_PROFILE_SELECT';

export const BASIC_INFO_LIST = 'BASIC_INFO_LIST';
export const BASIC_INFO_CREATE = 'BASIC_INFO_CREATE';
export const BASIC_INFO_UPDATE = 'BASIC_INFO_UPDATE';
export const BASIC_INFO_SHOW_EDIT_MODAL = 'BASIC_INFO_SHOW_EDIT_MODAL';
export const BASIC_INFO_HIDE_EDIT_MODAL = 'BASIC_INFO_HIDE_EDIT_MODAL';

export const WORK_HISTORY_LIST = 'WORK_HISTORY_LIST';
export const WORK_HISTORY_CREATE = 'WORK_HISTORY_CREATE';
export const WORK_HISTORY_UPDATE = 'WORK_HISTORY_UPDATE';
export const WORK_HISTORY_DELETE = 'WORK_HISTORY_DELETE';
export const WORK_HISTORY_SHOW_EDIT_MODAL = 'WORK_HISTORY_SHOW_EDIT_MODAL';
export const WORK_HISTORY_HIDE_EDIT_MODAL = 'WORK_HISTORY_HIDE_EDIT_MODAL';

export const EDUCATION_LIST = 'EDUCATION_LIST';
export const EDUCATION_CREATE = 'EDUCATION_CREATE';
export const EDUCATION_UPDATE = 'EDUCATION_UPDATE';
export const EDUCATION_DELETE = 'EDUCATION_DELETE';
export const EDUCATION_SHOW_EDIT_MODAL = 'EDUCATION_SHOW_EDIT_MODAL';
export const EDUCATION_HIDE_EDIT_MODAL = 'EDUCATION_HIDE_EDIT_MODAL';

export const LANGUAGE_LIST = 'LANGUAGE_LIST';
export const LANGUAGE_CREATE = 'LANGUAGE_CREATE';
export const LANGUAGE_UPDATE = 'LANGUAGE_UPDATE';
export const LANGUAGE_DELETE = 'LANGUAGE_DELETE';
export const LANGUAGE_SHOW_EDIT_MODAL = 'LANGUAGE_SHOW_EDIT_MODAL';
export const LANGUAGE_HIDE_EDIT_MODAL = 'LANGUAGE_HIDE_EDIT_MODAL';

export const SEARCH_PREFERENCE_LIST = 'SEARCH_PREFERENCE_LIST';
export const SEARCH_PREFERENCE_CREATE = 'SEARCH_PREFERENCE_CREATE';
export const SEARCH_PREFERENCE_UPDATE = 'SEARCH_PREFERENCE_UPDATE';

export const LOOKING_FOR_LIST = 'LOOKING_FOR_LIST';
export const LOCATION_LIST = 'LOCATION_LIST';
export const INDUSTRY_LIST = 'INDUSTRY_LIST';
export const ROLE_LIST = 'ROLE_LIST';
export const COUNTRY_LIST = 'COUNTRY_LIST';
export const STATE_LIST = 'STATE_LIST';
export const CITY_LIST = 'CITY_LIST';

export const VACANCY_LIST = 'VACANCY_LIST';
export const VACANCY_CREATE = 'VACANCY_CREATE';
export const VACANCY_UPDATE = 'VACANCY_UPDATE';
export const VACANCY_DELETE = 'VACANCY_DELETE';
export const APPLY_SEARCH_FILTERS = 'APPLY_SEARCH_FILTERS';
export const VACANCY_STANDARD_SEARCH = 'VACANCY_STANDARD_SEARCH';
export const VACANCY_PERSONALIZED_SEARCH = 'VACANCY_PERSONALIZED_SEARCH';
