# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-05 01:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalSkill',
            fields=[
                ('skill_id', models.AutoField(primary_key=True, serialize=False)),
                ('skill', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'skills',
            },
        ),
    ]
