# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-05 02:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_externalskill'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalRole',
            fields=[
                ('title_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField(blank=True, null=True)),
                ('title_tally', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'titles_clean',
            },
        ),
    ]
