# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-12 12:01
from __future__ import unicode_literals

import array_field_select.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import sample.job_profiles.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BasicInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=sample.job_profiles.models.BasicInfo.photo_directory_path)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('linkedin', models.URLField(blank=True)),
                ('address1', models.CharField(blank=True, max_length=255)),
                ('address2', models.CharField(blank=True, max_length=255)),
                ('address3', models.CharField(blank=True, max_length=255)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=255)),
                ('degree', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ('start_date', 'end_date'),
            },
        ),
        migrations.CreateModel(
            name='JobProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cv', models.FileField(blank=True, null=True, upload_to=sample.job_profiles.models.JobProfile.cv_directory_path)),
                ('name', models.CharField(max_length=255)),
                ('is_published', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_profiles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('level', models.IntegerField(choices=[(0, 'Basic'), (1, 'Business'), (2, 'Fluent')], default=2)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('job_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='job_profiles.JobProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Preferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('looking_for', array_field_select.fields.ArrayField(base_field=models.IntegerField(blank=True, choices=[(0, 'Full Time'), (1, 'Part Time'), (2, 'Contract'), (3, 'Permanent'), (4, 'Temporary')], null=True), blank=True, default=[], null=True, size=None)),
                ('weekly_email', models.BooleanField(default=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('industries', models.ManyToManyField(blank=True, related_name='industries', to='common.Industry')),
                ('job_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='job_profiles.JobProfile')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='common.Location')),
                ('roles', models.ManyToManyField(blank=True, related_name='roles', to='common.Role')),
            ],
        ),
        migrations.CreateModel(
            name='WorkHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('descr', models.TextField(blank=True)),
                ('job_type', models.IntegerField(choices=[(0, 'Full Time'), (1, 'Part Time'), (2, 'Contract'), (3, 'Permanent'), (4, 'Temporary')], default=0)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('job_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_histories', to='job_profiles.JobProfile')),
            ],
            options={
                'ordering': ('start_date', 'end_date'),
            },
        ),
        migrations.AddField(
            model_name='education',
            name='job_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='job_profiles.JobProfile'),
        ),
        migrations.AddField(
            model_name='basicinfo',
            name='job_profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='basic_info', to='job_profiles.JobProfile'),
        ),
    ]
