# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-29 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobprofile',
            options={'ordering': ('-modified', 'name')},
        ),
        migrations.AddField(
            model_name='jobprofile',
            name='cv_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobprofile',
            name='cv_content_hash',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobprofile',
            name='cv_hash',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
