# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-07 07:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vacancies', '0001_initial'),
        ('job_profiles', '0002_auto_20180129_1733'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalJobProfile',
            fields=[
                ('cv_id', models.AutoField(primary_key=True, serialize=False)),
                ('cv_content', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cvs',
            },
        ),
        migrations.CreateModel(
            name='ExternalVacancy',
            fields=[
                ('job_id', models.AutoField(primary_key=True, serialize=False)),
                ('job_posting', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'jobs',
            },
        ),
        migrations.CreateModel(
            name='JobProfileMatching',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.IntegerField()),
                ('job_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_profiles.JobProfile')),
            ],
            options={
                'db_table': 'search_jobprofile_matching',
            },
        ),
        migrations.CreateModel(
            name='JobProfileVacancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=6, max_digits=15)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('job_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_profiles.JobProfile')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacancies.Vacancy')),
            ],
            options={
                'db_table': 'search_jobprofile_vacancy',
                'ordering': ('-score',),
            },
        ),
        migrations.CreateModel(
            name='VacancyMatching',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.IntegerField()),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacancies.Vacancy')),
            ],
            options={
                'db_table': 'search_vacancy_matching',
            },
        ),
        migrations.CreateModel(
            name='ExternalJobProfileVacancy',
            fields=[
                ('cv', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='search.ExternalJobProfile')),
                ('match_score', models.DecimalField(decimal_places=6, max_digits=15)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='search.ExternalVacancy')),
            ],
            options={
                'db_table': 'cand_job_matches',
            },
        ),
        migrations.AlterUniqueTogether(
            name='vacancymatching',
            unique_together=set([('vacancy', 'external_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='jobprofilevacancy',
            unique_together=set([('job_profile', 'vacancy')]),
        ),
        migrations.AlterUniqueTogether(
            name='jobprofilematching',
            unique_together=set([('job_profile', 'external_id')]),
        ),
    ]
